global using HR.Common;
global using HR.Common.Domain;
global using HR.Common.Middleware;
global using HR.Common.Results;
global using HR.Common.Exceptions;
global using HR.Common.Persistence;
global using HR.Common.CQRS;
global using HR.Common.Dto;
global using HR.Common.Pagination;
global using HR.Employee.Domain;
global using HR.Employee.Application.Dtos;
global using HR.Employee.Infrastructure.Persistence;
global using MediatR;
global using FluentValidation;
global using Microsoft.EntityFrameworkCore;
global using MapsterMapper;
global using Serilog;
global using IMapper = MapsterMapper.IMapper;
